# Generated by Django 3.2.8 on 2021-12-20 15:23

import MatchesHandler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchesHandler', '0002_newsfeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfeed',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=MatchesHandler.models.upload_to),
        ),
    ]
