# Generated by Django 3.2.8 on 2021-12-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchesHandler', '0004_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='dateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
