# Generated by Django 3.2.8 on 2022-01-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchesHandler', '0005_invite_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='sentTo',
            field=models.CharField(max_length=100),
        ),
    ]
