# Generated by Django 3.2.8 on 2021-10-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserHandler', '0002_details_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='latitude',
            field=models.DecimalField(decimal_places=9, max_digits=12),
        ),
        migrations.AlterField(
            model_name='details',
            name='longitude',
            field=models.DecimalField(decimal_places=9, max_digits=12),
        ),
    ]
