# Generated by Django 3.2.8 on 2021-11-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserHandler', '0003_auto_20211022_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='profileImg',
            field=models.ImageField(blank=True, null=True, upload_to='media/profilePics'),
        ),
    ]
