# Generated by Django 3.2.8 on 2021-11-09 13:29

import UserHandler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserHandler', '0004_details_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='profileImg',
            field=models.ImageField(blank=True, null=True, upload_to=UserHandler.models.upload_to),
        ),
    ]
