# Generated by Django 3.2.8 on 2021-12-13 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserHandler', '0005_alter_details_profileimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='setPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=9, max_digits=12)),
                ('ageMin', models.DecimalField(decimal_places=9, max_digits=12)),
                ('ageMax', models.DecimalField(decimal_places=9, max_digits=12)),
                ('gender', models.CharField(max_length=20)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
