# Generated by Django 3.2.8 on 2021-12-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserHandler', '0006_setpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setpreference',
            name='ageMax',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='setpreference',
            name='ageMin',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='setpreference',
            name='distance',
            field=models.IntegerField(max_length=3),
        ),
    ]
